// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covi.Client.Services.Platform.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ChangeRequest
    {
        /// <summary>
        /// Initializes a new instance of the ChangeRequest class.
        /// </summary>
        public ChangeRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ChangeRequest class.
        /// </summary>
        public ChangeRequest(int statusId, System.DateTime statusChangedOn, string comment = default(string))
        {
            StatusId = statusId;
            StatusChangedOn = statusChangedOn;
            Comment = comment;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "statusId")]
        public int StatusId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "statusChangedOn")]
        public System.DateTime StatusChangedOn { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "comment")]
        public string Comment { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
