// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covi.Client.Services.Platform.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MedicalCode
    {
        /// <summary>
        /// Initializes a new instance of the MedicalCode class.
        /// </summary>
        public MedicalCode()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MedicalCode class.
        /// </summary>
        /// <param name="medicalCodeProperty">One-time-use medical code</param>
        public MedicalCode(string medicalCodeProperty = default(string), System.DateTime? expiresAt = default(System.DateTime?))
        {
            MedicalCodeProperty = medicalCodeProperty;
            ExpiresAt = expiresAt;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets one-time-use medical code
        /// </summary>
        [JsonProperty(PropertyName = "medicalCode")]
        public string MedicalCodeProperty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "expiresAt")]
        public System.DateTime? ExpiresAt { get; set; }

    }
}
