// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covi.Client.Services.Platform.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Meeting
    {
        /// <summary>
        /// Initializes a new instance of the Meeting class.
        /// </summary>
        public Meeting()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Meeting class.
        /// </summary>
        public Meeting(string userToken, System.DateTime timestamp)
        {
            UserToken = userToken;
            Timestamp = timestamp;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userToken")]
        public string UserToken { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timestamp")]
        public System.DateTime Timestamp { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (UserToken == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "UserToken");
            }
        }
    }
}
