// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covi.Client.Services.Platform.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class RecommendationsList
    {
        /// <summary>
        /// Initializes a new instance of the RecommendationsList class.
        /// </summary>
        public RecommendationsList()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RecommendationsList class.
        /// </summary>
        public RecommendationsList(string status = default(string), IList<Recommendation> data = default(IList<Recommendation>))
        {
            Status = status;
            Data = data;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "data")]
        public IList<Recommendation> Data { get; set; }

    }
}
