// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covi.Client.Services.Platform.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Recommendation
    {
        /// <summary>
        /// Initializes a new instance of the Recommendation class.
        /// </summary>
        public Recommendation()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Recommendation class.
        /// </summary>
        public Recommendation(string title = default(string), string subTitle = default(string), string description = default(string))
        {
            Title = title;
            SubTitle = subTitle;
            Description = description;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "subTitle")]
        public string SubTitle { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

    }
}
