// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covi.Client.Services.Platform.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RefreshTokenRequest
    {
        /// <summary>
        /// Initializes a new instance of the RefreshTokenRequest class.
        /// </summary>
        public RefreshTokenRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RefreshTokenRequest class.
        /// </summary>
        public RefreshTokenRequest(string refreshToken)
        {
            RefreshToken = refreshToken;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "refreshToken")]
        public string RefreshToken { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (RefreshToken == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "RefreshToken");
            }
        }
    }
}
