// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covi.Client.Services.Platform.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RegisterDoctorRequest
    {
        /// <summary>
        /// Initializes a new instance of the RegisterDoctorRequest class.
        /// </summary>
        public RegisterDoctorRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RegisterDoctorRequest class.
        /// </summary>
        public RegisterDoctorRequest(string healthSecurityId)
        {
            HealthSecurityId = healthSecurityId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "healthSecurityId")]
        public string HealthSecurityId { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (HealthSecurityId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "HealthSecurityId");
            }
        }
    }
}
