// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covi.Client.Services.Platform.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Token
    {
        /// <summary>
        /// Initializes a new instance of the Token class.
        /// </summary>
        public Token()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Token class.
        /// </summary>
        public Token(string accessToken = default(string), string refreshToken = default(string), int? expiresIn = default(int?))
        {
            AccessToken = accessToken;
            RefreshToken = refreshToken;
            ExpiresIn = expiresIn;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "accessToken")]
        public string AccessToken { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "refreshToken")]
        public string RefreshToken { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "expiresIn")]
        public int? ExpiresIn { get; set; }

    }
}
