//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Covi.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth Service..
        /// </summary>
        public static string Android_BluetoothNotification_ChannelName {
            get {
                return ResourceManager.GetString("Android_BluetoothNotification_ChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This device is discoverable to others nearby..
        /// </summary>
        public static string Android_BluetoothNotification_Content {
            get {
                return ResourceManager.GetString("Android_BluetoothNotification_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising device via Bluetooth!.
        /// </summary>
        public static string Android_BluetoothNotification_Title {
            get {
                return ResourceManager.GetString("Android_BluetoothNotification_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLY CODE.
        /// </summary>
        public static string ApplyCode_Btn_Text {
            get {
                return ResourceManager.GetString("ApplyCode_Btn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This code is not recognized.
        /// </summary>
        public static string ApplyCode_InputError_Text {
            get {
                return ResourceManager.GetString("ApplyCode_InputError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your code here.
        /// </summary>
        public static string ApplyCode_InputPlaceholder_Text {
            get {
                return ResourceManager.GetString("ApplyCode_InputPlaceholder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By continuing you are allowing us to inform others that they may be at risk of infection. This could save their life..
        /// </summary>
        public static string ApplyCode_PageDescription1_Text {
            get {
                return ResourceManager.GetString("ApplyCode_PageDescription1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember, this app never tracks your location or identity. You are completely anonymous..
        /// </summary>
        public static string ApplyCode_PageDescription2_Text {
            get {
                return ResourceManager.GetString("ApplyCode_PageDescription2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for helping keep others safe..
        /// </summary>
        public static string ApplyCode_PageDescription3_Text {
            get {
                return ResourceManager.GetString("ApplyCode_PageDescription3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for helping save lives.
        /// </summary>
        public static string ApplyCode_PageDescription4_Text {
            get {
                return ResourceManager.GetString("ApplyCode_PageDescription4_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your code.
        /// </summary>
        public static string ApplyCode_PageName_Text {
            get {
                return ResourceManager.GetString("ApplyCode_PageName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the unique code your healthcare professional has given you. This will update your health status in this app..
        /// </summary>
        public static string ApplyCode_PageTitle1_Text {
            get {
                return ResourceManager.GetString("ApplyCode_PageTitle1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update your status and save lives.
        /// </summary>
        public static string ApplyCode_PageTitle2_Text {
            get {
                return ResourceManager.GetString("ApplyCode_PageTitle2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical code is expired..
        /// </summary>
        public static string ApplyCodeExpiredException_ErrorText {
            get {
                return ResourceManager.GetString("ApplyCodeExpiredException_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical code not found or already taken..
        /// </summary>
        public static string ApplyCodeNotFoundException_ErrorText {
            get {
                return ResourceManager.GetString("ApplyCodeNotFoundException_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open this app regularly when around others to enhance your bluetooth connectivity..
        /// </summary>
        public static string Bluetooth_Reminder_Description_Text {
            get {
                return ResourceManager.GetString("Bluetooth_Reminder_Description_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLUETOOTH CONNECTIVITY.
        /// </summary>
        public static string Bluetooth_Reminder_Title_Text {
            get {
                return ResourceManager.GetString("Bluetooth_Reminder_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission to use bluetooth was denied. Please, grant permission to use bluetooth in the application settings to proceed..
        /// </summary>
        public static string BluetoothNotification_Denied_ErrorText {
            get {
                return ResourceManager.GetString("BluetoothNotification_Denied_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth is currently unavailable. Either bluetooth is not supported by your device or it is disabled. Please, check device bluetooth settings..
        /// </summary>
        public static string BluetoothNotification_Disabled_ErrorText {
            get {
                return ResourceManager.GetString("BluetoothNotification_Disabled_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth error..
        /// </summary>
        public static string BluetoothNotification_Error_Title {
            get {
                return ResourceManager.GetString("BluetoothNotification_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The StatusChangedOn field is required..
        /// </summary>
        public static string ChangeStatusCodeGenerationException_StatusChangedOn_ErrorText {
            get {
                return ResourceManager.GetString("ChangeStatusCodeGenerationException_StatusChangedOn_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The StatusId field is required..
        /// </summary>
        public static string ChangeStatusCodeGenerationException_StatusId_ErrorText {
            get {
                return ResourceManager.GetString("ChangeStatusCodeGenerationException_StatusId_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE STATUS.
        /// </summary>
        public static string ChangeStatusLink_Button_Text {
            get {
                return ResourceManager.GetString("ChangeStatusLink_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the link below to update your health status.
        /// </summary>
        public static string ChangeStatusLink_Explanation_Text {
            get {
                return ResourceManager.GetString("ChangeStatusLink_Explanation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string CreateProfile_AlreadyHaveAnAccount_Text {
            get {
                return ResourceManager.GetString("CreateProfile_AlreadyHaveAnAccount_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string CreateProfile_Confirm_Password_Text {
            get {
                return ResourceManager.GetString("CreateProfile_Confirm_Password_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string CreateProfile_LoginBtn_Text {
            get {
                return ResourceManager.GetString("CreateProfile_LoginBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEXT.
        /// </summary>
        public static string CreateProfile_Next_Button_Text {
            get {
                return ResourceManager.GetString("CreateProfile_Next_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create profile.
        /// </summary>
        public static string CreateProfile_PageName_Text {
            get {
                return ResourceManager.GetString("CreateProfile_PageName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string CreateProfile_Password_Text {
            get {
                return ResourceManager.GetString("CreateProfile_Password_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password requirements.
        /// </summary>
        public static string CreateProfile_PasswordRequirements_Text {
            get {
                return ResourceManager.GetString("CreateProfile_PasswordRequirements_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 8 characters.
        /// </summary>
        public static string CreateProfile_Requirement_1_Text {
            get {
                return ResourceManager.GetString("CreateProfile_Requirement_1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contain one upper case letter.
        /// </summary>
        public static string CreateProfile_Requirement_2_Text {
            get {
                return ResourceManager.GetString("CreateProfile_Requirement_2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contain one lower case letter.
        /// </summary>
        public static string CreateProfile_Requirement_3_Text {
            get {
                return ResourceManager.GetString("CreateProfile_Requirement_3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contain one special symbol.
        /// </summary>
        public static string CreateProfile_Requirement_4_Text {
            get {
                return ResourceManager.GetString("CreateProfile_Requirement_4_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username should not be empty..
        /// </summary>
        public static string CreateProfile_Requirement_Filled_Username_Text {
            get {
                return ResourceManager.GetString("CreateProfile_Requirement_Filled_Username_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirmation password should be the same..
        /// </summary>
        public static string CreateProfile_Requirement_Same_Passwords_Text {
            get {
                return ResourceManager.GetString("CreateProfile_Requirement_Same_Passwords_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a free anonymous profile.
        /// </summary>
        public static string CreateProfile_Title_Text {
            get {
                return ResourceManager.GetString("CreateProfile_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string CreateProfile_Username_Entry_Placeholder_Text {
            get {
                return ResourceManager.GetString("CreateProfile_Username_Entry_Placeholder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is already taken..
        /// </summary>
        public static string CreateProfileValidationException_DuplicateUserName_ErrorText {
            get {
                return ResourceManager.GetString("CreateProfileValidationException_DuplicateUserName_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user token is already taken..
        /// </summary>
        public static string CreateProfileValidationException_DuplicateUserToken_ErrorText {
            get {
                return ResourceManager.GetString("CreateProfileValidationException_DuplicateUserToken_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password field is require.
        /// </summary>
        public static string CreateProfileValidationException_Password_ErrorText {
            get {
                return ResourceManager.GetString("CreateProfileValidationException_Password_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one digit (&apos;0&apos;-&apos;9&apos;)..
        /// </summary>
        public static string CreateProfileValidationException_PasswordRequiresDigit_ErrorText {
            get {
                return ResourceManager.GetString("CreateProfileValidationException_PasswordRequiresDigit_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one non alphanumeric character..
        /// </summary>
        public static string CreateProfileValidationException_PasswordRequiresNonAlphanumeric_ErrorText {
            get {
                return ResourceManager.GetString("CreateProfileValidationException_PasswordRequiresNonAlphanumeric_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one uppercase (&apos;A&apos;-&apos;Z&apos;)..
        /// </summary>
        public static string CreateProfileValidationException_PasswordRequiresUpper_ErrorText {
            get {
                return ResourceManager.GetString("CreateProfileValidationException_PasswordRequiresUpper_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must be at least 8 characters..
        /// </summary>
        public static string CreateProfileValidationException_PasswordTooShort_ErrorText {
            get {
                return ResourceManager.GetString("CreateProfileValidationException_PasswordTooShort_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UserToken field is required..
        /// </summary>
        public static string CreateProfileValidationException_TokenIsEmpty_ErrorText {
            get {
                return ResourceManager.GetString("CreateProfileValidationException_TokenIsEmpty_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Username field is required..
        /// </summary>
        public static string CreateProfileValidationException_Username_ErrorText {
            get {
                return ResourceManager.GetString("CreateProfileValidationException_Username_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special characters in username are not allowed.
        /// </summary>
        public static string CreateProfileValidationException_Username_HasSpecialSymbolErrorText {
            get {
                return ResourceManager.GetString("CreateProfileValidationException_Username_HasSpecialSymbolErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All information in this app is encrypted and  totally anonymous..
        /// </summary>
        public static string Encryption_Status_Description_Text {
            get {
                return ResourceManager.GetString("Encryption_Status_Description_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENCRYPTION.
        /// </summary>
        public static string Encryption_Status_Title_Text {
            get {
                return ResourceManager.GetString("Encryption_Status_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ErrorDialog_Accept {
            get {
                return ResourceManager.GetString("ErrorDialog_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again later..
        /// </summary>
        public static string ErrorDialog_Message_Generic {
            get {
                return ResourceManager.GetString("ErrorDialog_Message_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorDialog_Title {
            get {
                return ResourceManager.GetString("ErrorDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection is not available..
        /// </summary>
        public static string Exception_NoInternetConnection {
            get {
                return ResourceManager.GetString("Exception_NoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection timed out, please try again later..
        /// </summary>
        public static string Exception_TimedOut_Text {
            get {
                return ResourceManager.GetString("Exception_TimedOut_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under maintenance.
        /// </summary>
        public static string Exception_UnderMaintenance {
            get {
                return ResourceManager.GetString("Exception_UnderMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops!.
        /// </summary>
        public static string Exception_Unknown {
            get {
                return ResourceManager.GetString("Exception_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update required.
        /// </summary>
        public static string Exception_UpdateRequired {
            get {
                return ResourceManager.GetString("Exception_UpdateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPAM Systems.
        /// </summary>
        public static string Global_EPAM_Text {
            get {
                return ResourceManager.GetString("Global_EPAM_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by .
        /// </summary>
        public static string Global_PoweredBy_Text {
            get {
                return ResourceManager.GetString("Global_PoweredBy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Health Status is: {0}.  To stay safe, please follow the government guidlines and recommendations..
        /// </summary>
        public static string HealthStatus_Advice_Description_Default_TextFormat {
            get {
                return ResourceManager.GetString("HealthStatus_Advice_Description_Default_TextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find out more.
        /// </summary>
        public static string HealthStatus_Advice_MoreInfo_Text {
            get {
                return ResourceManager.GetString("HealthStatus_Advice_MoreInfo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATTENTION.
        /// </summary>
        public static string HealthStatus_Advice_Title_Text {
            get {
                return ResourceManager.GetString("HealthStatus_Advice_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password not recognised..
        /// </summary>
        public static string LoginException_InvalidGrant_ErrorText {
            get {
                return ResourceManager.GetString("LoginException_InvalidGrant_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under maintenance.
        /// </summary>
        public static string Maintenance_Description_Text {
            get {
                return ResourceManager.GetString("Maintenance_Description_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consent Request.
        /// </summary>
        public static string Maps_ConsentRequest_Text {
            get {
                return ResourceManager.GetString("Maps_ConsentRequest_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you! You have help to prevent spreading COVID-19..
        /// </summary>
        public static string Maps_ConsentSuccess_Text {
            get {
                return ResourceManager.GetString("Maps_ConsentSuccess_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string Maps_ConsentSuccessTitle_Text {
            get {
                return ResourceManager.GetString("Maps_ConsentSuccessTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot Location.
        /// </summary>
        public static string Maps_HotLocation_Text {
            get {
                return ResourceManager.GetString("Maps_HotLocation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infected.
        /// </summary>
        public static string Maps_Infected_Text {
            get {
                return ResourceManager.GetString("Maps_Infected_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In quarantine.
        /// </summary>
        public static string Maps_InQuarantine_Text {
            get {
                return ResourceManager.GetString("Maps_InQuarantine_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps.
        /// </summary>
        public static string Maps_Title_Text {
            get {
                return ResourceManager.GetString("Maps_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Location.
        /// </summary>
        public static string Maps_YouLocation_Text {
            get {
                return ResourceManager.GetString("Maps_YouLocation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE CODE.
        /// </summary>
        public static string Medical_CreateCodeBtn_Text {
            get {
                return ResourceManager.GetString("Medical_CreateCodeBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +Edit.
        /// </summary>
        public static string Medical_EditBtn_Text {
            get {
                return ResourceManager.GetString("Medical_EditBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the status for the code.
        /// </summary>
        public static string Medical_FirstStep_Description {
            get {
                return ResourceManager.GetString("Medical_FirstStep_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 01.
        /// </summary>
        public static string Medical_FirstStep_Title {
            get {
                return ResourceManager.GetString("Medical_FirstStep_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the patients status.
        /// </summary>
        public static string Medical_FirstStepEmpty_Error {
            get {
                return ResourceManager.GetString("Medical_FirstStepEmpty_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select when the patient approximately first became infected.
        /// </summary>
        public static string Medical_SecondStep_Description {
            get {
                return ResourceManager.GetString("Medical_SecondStep_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 02.
        /// </summary>
        public static string Medical_SecondStep_Title {
            get {
                return ResourceManager.GetString("Medical_SecondStep_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate patient code.
        /// </summary>
        public static string Medical_ThirdStep_Description {
            get {
                return ResourceManager.GetString("Medical_ThirdStep_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 03.
        /// </summary>
        public static string Medical_ThirdStep_Title {
            get {
                return ResourceManager.GetString("Medical_ThirdStep_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical.
        /// </summary>
        public static string Medical_Title_Text {
            get {
                return ResourceManager.GetString("Medical_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DONE.
        /// </summary>
        public static string MedicalActivated_Btn_Text {
            get {
                return ResourceManager.GetString("MedicalActivated_Btn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have now activated the medical section of the app.
        /// </summary>
        public static string MedicalActivated_MainLabel_Text {
            get {
                return ResourceManager.GetString("MedicalActivated_MainLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can generate codes to send to your patients, so as they can update their status.
        /// </summary>
        public static string MedicalActivated_SecondaryLabel_Text {
            get {
                return ResourceManager.GetString("MedicalActivated_SecondaryLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you.
        /// </summary>
        public static string MedicalActivated_ThankyouLabel_Text {
            get {
                return ResourceManager.GetString("MedicalActivated_ThankyouLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health security id is already taken or expired..
        /// </summary>
        public static string MedicalAuthenticationException_InvalidHealthSecurityId_ErrorText {
            get {
                return ResourceManager.GetString("MedicalAuthenticationException_InvalidHealthSecurityId_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap code to copy and send to your patient so as they can change their status.
        /// </summary>
        public static string MedicalCodeSharing_CodeLabel_Text {
            get {
                return ResourceManager.GetString("MedicalCodeSharing_CodeLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code generator.
        /// </summary>
        public static string MedicalCodeSharing_PageName_Text {
            get {
                return ResourceManager.GetString("MedicalCodeSharing_PageName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHARE CODE.
        /// </summary>
        public static string MedicalCodeSharing_ShareBtn_Text {
            get {
                return ResourceManager.GetString("MedicalCodeSharing_ShareBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Code.
        /// </summary>
        public static string MedicalCodeSharing_ShareSystem_TitleText {
            get {
                return ResourceManager.GetString("MedicalCodeSharing_ShareSystem_TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please find your code for the following status:.
        /// </summary>
        public static string MedicalCodeSharing_Title_Text {
            get {
                return ResourceManager.GetString("MedicalCodeSharing_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTINUE.
        /// </summary>
        public static string MedicalLogIn_Btn_Text {
            get {
                return ResourceManager.GetString("MedicalLogIn_Btn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health security ID.
        /// </summary>
        public static string MedicalLogIn_Entry_Placeholder_Text {
            get {
                return ResourceManager.GetString("MedicalLogIn_Entry_Placeholder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health ID not recognized.
        /// </summary>
        public static string MedicalLogIn_Entry_Requirements_Text {
            get {
                return ResourceManager.GetString("MedicalLogIn_Entry_Requirements_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Id should not be empty.
        /// </summary>
        public static string MedicalLogIn_MedicalId_EmptyErrorMessage_Text {
            get {
                return ResourceManager.GetString("MedicalLogIn_MedicalId_EmptyErrorMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional.
        /// </summary>
        public static string MedicalLogIn_PageName_Text {
            get {
                return ResourceManager.GetString("MedicalLogIn_PageName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section of the app is for healthcare professionals only. Please enter your health security ID to continue..
        /// </summary>
        public static string MedicalLogIn_Title_Text {
            get {
                return ResourceManager.GetString("MedicalLogIn_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow.
        /// </summary>
        public static string Notification_Allow_Text {
            get {
                return ResourceManager.GetString("Notification_Allow_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COVID Resistance would like to make data available to nearby Bluetooth devices even when you&apos;re not using the app..
        /// </summary>
        public static string Notification_BluetoothNotification_Text {
            get {
                return ResourceManager.GetString("Notification_BluetoothNotification_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t allow.
        /// </summary>
        public static string Notification_DontAllow_Text {
            get {
                return ResourceManager.GetString("Notification_DontAllow_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow COVID Resistance to send you notifications?.
        /// </summary>
        public static string Notification_InAppNotification_Text {
            get {
                return ResourceManager.GetString("Notification_InAppNotification_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Notification_Retry_Text {
            get {
                return ResourceManager.GetString("Notification_Retry_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tailored for you.
        /// </summary>
        public static string OnBoardind_MadeForYou_SubTitle {
            get {
                return ResourceManager.GetString("OnBoardind_MadeForYou_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For this app to work and help save lives, please connect with bluetooth.
        /// </summary>
        public static string OnBoarding_Connectivity_ErrorText {
            get {
                return ResourceManager.GetString("OnBoarding_Connectivity_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100% anonymous.
        /// </summary>
        public static string OnBoarding_Connectivity_Instruction1 {
            get {
                return ResourceManager.GetString("OnBoarding_Connectivity_Instruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using bluetooth to know if you’ve been near someone who is infected.
        /// </summary>
        public static string OnBoarding_Connectivity_Instruction2 {
            get {
                return ResourceManager.GetString("OnBoarding_Connectivity_Instruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No geo location.
        /// </summary>
        public static string OnBoarding_Connectivity_Instruction3 {
            get {
                return ResourceManager.GetString("OnBoarding_Connectivity_Instruction3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will only use the bluetooth and not the location when you give permission.
        /// </summary>
        public static string OnBoarding_Connectivity_Instruction4_AndroidOnly {
            get {
                return ResourceManager.GetString("OnBoarding_Connectivity_Instruction4_AndroidOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect with Bluetooth.
        /// </summary>
        public static string OnBoarding_Connectivity_SubTitle {
            get {
                return ResourceManager.GetString("OnBoarding_Connectivity_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectivity.
        /// </summary>
        public static string OnBoarding_Connectivity_Title {
            get {
                return ResourceManager.GetString("OnBoarding_Connectivity_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendations tailored to your profile category.
        /// </summary>
        public static string OnBoarding_MadeForYou_Instruction1 {
            get {
                return ResourceManager.GetString("OnBoarding_MadeForYou_Instruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area specific risks, recommendations and behaviour rules.
        /// </summary>
        public static string OnBoarding_MadeForYou_Instruction2 {
            get {
                return ResourceManager.GetString("OnBoarding_MadeForYou_Instruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO private information shared.
        /// </summary>
        public static string OnBoarding_MadeForYou_Instruction3 {
            get {
                return ResourceManager.GetString("OnBoarding_MadeForYou_Instruction3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made for you.
        /// </summary>
        public static string OnBoarding_MadeForYou_Title {
            get {
                return ResourceManager.GetString("OnBoarding_MadeForYou_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For this app to work and help save lives, please allow notifications.
        /// </summary>
        public static string OnBoarding_Notifications_ErrorText {
            get {
                return ResourceManager.GetString("OnBoarding_Notifications_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications that inform you if you’ve been near someone infected.
        /// </summary>
        public static string OnBoarding_Notifications_Instruction1 {
            get {
                return ResourceManager.GetString("OnBoarding_Notifications_Instruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO emails.
        /// </summary>
        public static string OnBoarding_Notifications_Instruction2 {
            get {
                return ResourceManager.GetString("OnBoarding_Notifications_Instruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO texts.
        /// </summary>
        public static string OnBoarding_Notifications_Instruction3 {
            get {
                return ResourceManager.GetString("OnBoarding_Notifications_Instruction3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications sent through the app only.
        /// </summary>
        public static string OnBoarding_Notifications_Instruction4 {
            get {
                return ResourceManager.GetString("OnBoarding_Notifications_Instruction4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important notifications.
        /// </summary>
        public static string OnBoarding_Notifications_SubTitle {
            get {
                return ResourceManager.GetString("OnBoarding_Notifications_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string OnBoarding_Notifications_Title {
            get {
                return ResourceManager.GetString("OnBoarding_Notifications_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All information transmitted via encryption.
        /// </summary>
        public static string OnBoarding_Privacy_Instruction1 {
            get {
                return ResourceManager.GetString("OnBoarding_Privacy_Instruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO information is linked to your identity.
        /// </summary>
        public static string OnBoarding_Privacy_Instruction2 {
            get {
                return ResourceManager.GetString("OnBoarding_Privacy_Instruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO personal information leaves your phone.
        /// </summary>
        public static string OnBoarding_Privacy_Instruction3 {
            get {
                return ResourceManager.GetString("OnBoarding_Privacy_Instruction3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completely anonymous.
        /// </summary>
        public static string OnBoarding_Privacy_SubTitle {
            get {
                return ResourceManager.GetString("OnBoarding_Privacy_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string OnBoarding_Privacy_Title {
            get {
                return ResourceManager.GetString("OnBoarding_Privacy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elderly (65+ years old).
        /// </summary>
        public static string Profile_AgeGroup_Elderly_Text {
            get {
                return ResourceManager.GetString("Profile_AgeGroup_Elderly_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age group.
        /// </summary>
        public static string Profile_AgeGroup_Text {
            get {
                return ResourceManager.GetString("Profile_AgeGroup_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLY CODE.
        /// </summary>
        public static string Profile_ApplyCodeBtn_Text {
            get {
                return ResourceManager.GetString("Profile_ApplyCodeBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Profile_Country_Text {
            get {
                return ResourceManager.GetString("Profile_Country_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY STATUS:.
        /// </summary>
        public static string Profile_MyStatus_Text {
            get {
                return ResourceManager.GetString("Profile_MyStatus_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VirusFighter007.
        /// </summary>
        public static string Profile_Nickname_Text {
            get {
                return ResourceManager.GetString("Profile_Nickname_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERSONAL DATA.
        /// </summary>
        public static string Profile_PersonalData_Text {
            get {
                return ResourceManager.GetString("Profile_PersonalData_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gather personalized info by inputting your data for your demographic group..
        /// </summary>
        public static string Profile_PersonalDataDescription_Text {
            get {
                return ResourceManager.GetString("Profile_PersonalDataDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string Profile_PhoneNumber_Text {
            get {
                return ResourceManager.GetString("Profile_PhoneNumber_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code.
        /// </summary>
        public static string Profile_PostalCode_Text {
            get {
                return ResourceManager.GetString("Profile_PostalCode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-conditions.
        /// </summary>
        public static string Profile_PreConditions_Text {
            get {
                return ResourceManager.GetString("Profile_PreConditions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile_Profile_Title_Text {
            get {
                return ResourceManager.GetString("Profile_Profile_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEXT.
        /// </summary>
        public static string Profile_ProfileTitle_Text {
            get {
                return ResourceManager.GetString("Profile_ProfileTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROTECTING.
        /// </summary>
        public static string Profile_Protecting_Text {
            get {
                return ResourceManager.GetString("Profile_Protecting_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate.
        /// </summary>
        public static string Shell_Corporate_Title_Text {
            get {
                return ResourceManager.GetString("Shell_Corporate_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Shell_Information_Title_Text {
            get {
                return ResourceManager.GetString("Shell_Information_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps.
        /// </summary>
        public static string Shell_Maps_Title_Text {
            get {
                return ResourceManager.GetString("Shell_Maps_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical.
        /// </summary>
        public static string Shell_Medical_Title_Text {
            get {
                return ResourceManager.GetString("Shell_Medical_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Shell_Profile_Title_Text {
            get {
                return ResourceManager.GetString("Shell_Profile_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health advice.
        /// </summary>
        public static string Shell_Recommendations_Title_Text {
            get {
                return ResourceManager.GetString("Shell_Recommendations_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string SignUp_AlreadyHaveAnAccount_Text {
            get {
                return ResourceManager.GetString("SignUp_AlreadyHaveAnAccount_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a free anonymous profile.
        /// </summary>
        public static string SignUp_Anon_Description_Text {
            get {
                return ResourceManager.GetString("SignUp_Anon_Description_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m an anonymous user.
        /// </summary>
        public static string SignUp_AnonymousOption_Text {
            get {
                return ResourceManager.GetString("SignUp_AnonymousOption_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE ACCOUNT.
        /// </summary>
        public static string SignUp_CreateAccountBtn_Text {
            get {
                return ResourceManager.GetString("SignUp_CreateAccountBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FMH/EAN identification number.
        /// </summary>
        public static string SignUp_IdNumber_Text {
            get {
                return ResourceManager.GetString("SignUp_IdNumber_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string SignUp_LoginBtn_Text {
            get {
                return ResourceManager.GetString("SignUp_LoginBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME.
        /// </summary>
        public static string SignUp_Name_Text {
            get {
                return ResourceManager.GetString("SignUp_Name_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a free account for physicians.
        /// </summary>
        public static string SignUp_Prof_Description_Text {
            get {
                return ResourceManager.GetString("SignUp_Prof_Description_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m a health professional.
        /// </summary>
        public static string SignUp_Professional_Text {
            get {
                return ResourceManager.GetString("SignUp_Professional_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSEUDONYM.
        /// </summary>
        public static string SignUp_Pseudonym_Text {
            get {
                return ResourceManager.GetString("SignUp_Pseudonym_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a secret nickname.
        /// </summary>
        public static string SignUp_SecretName_Text {
            get {
                return ResourceManager.GetString("SignUp_SecretName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sing Up.
        /// </summary>
        public static string SignUp_Title_Text {
            get {
                return ResourceManager.GetString("SignUp_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type here....
        /// </summary>
        public static string SignUp_TypeHerePlaceHolder_Text {
            get {
                return ResourceManager.GetString("SignUp_TypeHerePlaceHolder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completely Anonymous.
        /// </summary>
        public static string SignUpAnonInfo_CompletelyAnon_Text {
            get {
                return ResourceManager.GetString("SignUpAnonInfo_CompletelyAnon_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MADE FOR YOU.
        /// </summary>
        public static string SignUpAnonInfo_MadeForYou_Title_Text {
            get {
                return ResourceManager.GetString("SignUpAnonInfo_MadeForYou_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEXT.
        /// </summary>
        public static string SignUpAnonInfo_Next_Button_Text {
            get {
                return ResourceManager.GetString("SignUpAnonInfo_Next_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRIVACY.
        /// </summary>
        public static string SignUpAnonInfo_Privacy_Title_Text {
            get {
                return ResourceManager.GetString("SignUpAnonInfo_Privacy_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you input your profile data, your app will gather specific recommendations for your profile category. If you provide your postal code - your app will obtain specific information for your area (risks, recommendations, behavior rules)..
        /// </summary>
        public static string SignUpAnonInfo_TailoredDescription_Text {
            get {
                return ResourceManager.GetString("SignUpAnonInfo_TailoredDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tailored for you.
        /// </summary>
        public static string SignUpAnonInfo_TailoredForYou_Text {
            get {
                return ResourceManager.GetString("SignUpAnonInfo_TailoredForYou_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string SignUpMnemonic_AlreadyHaveAcc_Text {
            get {
                return ResourceManager.GetString("SignUpMnemonic_AlreadyHaveAcc_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string SignUpMnemonic_LogIn_Button_Text {
            get {
                return ResourceManager.GetString("SignUpMnemonic_LogIn_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your mnemonic phrase. Write it down in the correct order on a piece of paper. Do not take screenshot. Use this mnemonic phrase to login..
        /// </summary>
        public static string SignUpMnemonic_MnemonicPhraseDescription_Text {
            get {
                return ResourceManager.GetString("SignUpMnemonic_MnemonicPhraseDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COPIED.
        /// </summary>
        public static string SignUpMnemonic_NextPage_Button_Text {
            get {
                return ResourceManager.GetString("SignUpMnemonic_NextPage_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure you copied your phrase. You can&apos;t access your account without it..
        /// </summary>
        public static string SignUpMnemonic_Notification_Text {
            get {
                return ResourceManager.GetString("SignUpMnemonic_Notification_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        public static string SignUpMnemonic_NotificationDismiss_Text {
            get {
                return ResourceManager.GetString("SignUpMnemonic_NotificationDismiss_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COVID.
        /// </summary>
        public static string Splash_Crown_Text {
            get {
                return ResourceManager.GetString("Splash_Crown_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resistance.
        /// </summary>
        public static string Splash_Resistance_Text {
            get {
                return ResourceManager.GetString("Splash_Resistance_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG IN.
        /// </summary>
        public static string UserLogIn_Btn_Text {
            get {
                return ResourceManager.GetString("UserLogIn_Btn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserLogIn_NameEntry_Placeholder_Text {
            get {
                return ResourceManager.GetString("UserLogIn_NameEntry_Placeholder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string UserLogIn_PageName_Text {
            get {
                return ResourceManager.GetString("UserLogIn_PageName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should not be empty.
        /// </summary>
        public static string UserLogIn_Password_EmptyErrorMessage_Text {
            get {
                return ResourceManager.GetString("UserLogIn_Password_EmptyErrorMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string UserLogIn_PasswordEntry_Placeholder_Text {
            get {
                return ResourceManager.GetString("UserLogIn_PasswordEntry_Placeholder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password not recognized.
        /// </summary>
        public static string UserLogIn_PasswordEntry_Requirements_Text {
            get {
                return ResourceManager.GetString("UserLogIn_PasswordEntry_Requirements_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username should not be empty.
        /// </summary>
        public static string UserLogIn_Username_EmptyErrorMessage_Text {
            get {
                return ResourceManager.GetString("UserLogIn_Username_EmptyErrorMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} for {1} days.
        /// </summary>
        public static string UserStatus_StatusCountdown_TextFormat {
            get {
                return ResourceManager.GetString("UserStatus_StatusCountdown_TextFormat", resourceCulture);
            }
        }
    }
}
